# Generated by Django 4.2 on 2023-06-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_creds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un', models.CharField(max_length=50, verbose_name='Username')),
                ('pw', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
    ]
