# Generated by Django 4.2 on 2023-06-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('pno', models.CharField(max_length=50, verbose_name='pno')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('qual', models.CharField(max_length=50, verbose_name='qual')),
                ('stream', models.CharField(max_length=50, verbose_name='stream')),
                ('dyop', models.CharField(max_length=50, verbose_name='dyop')),
                ('dp', models.CharField(max_length=50, verbose_name='dp')),
                ('twp', models.CharField(max_length=50, verbose_name='twp')),
                ('tp', models.CharField(max_length=50, verbose_name='tp')),
            ],
        ),
    ]
