# Generated by Django 4.2 on 2023-06-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_mock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mock',
            old_name='by',
            new_name='Trainers',
        ),
    ]
